name: shopie
description: Shop the world.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_fonts:
  flutter_launcher_icons: ^0.7.5
  http:
  rflutter_alert: ^1.0.3
  flutter_typeahead:
  shared_preferences: ^0.5.8
  qrscan: 0.2.17
  image_picker: ^0.6.7+10
  modal_progress_hud:
  flutter_local_notifications: ^1.4.4+4
  notification_permissions: ^0.4.8
  video_player: any
  path_provider: ^1.6.22



dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/shopielogo2.png"


flutter:


  uses-material-design: true
  assets:
    - assets/logo/
    - assets/img/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
